name: Forge format and lint

on:
  pull_request:

env:
  FOUNDRY_PROFILE: default
  ARBITRUM_RPC_URL: https://arbitrum.gateway.tenderly.co

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1
        with:
          version: 1.3.5
          cache: true

      - name: Check formatting
        run: forge fmt --check

      - name: Run linter
        run: forge lint
